name: build c++20

on:
  push:
  pull_request:

jobs:
  build-gcc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install gcc-10 g++-10
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-10
           make
  build-clang:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-14
           make
  build-msvc:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=cl
           make
